name: Haskell CI

on:
  push: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: haskell/ghcup-setup@v1

      - name: Update package index
        run: cabal update

      - name: Build
        run: cabal build all

      - name: Run tests
        run: cabal test all --test-show-details=direct